# TCL File Generated by Component Editor 17.1
# Sat Feb 03 20:48:30 BRT 2018
# DO NOT MODIFY


#
# I2C_Stream "I2C Stream" v1.0
# packet based streaming i2c interface
#

#
# request TCL package from ACDS 16.1
#
package require -exact qsys 16.1


#
# module I2C_Stream
#
set_module_property  DESCRIPTION                   "packet based streaming i2c interface"
set_module_property  NAME                          I2C_Stream
set_module_property  VERSION                       1.0
set_module_property  INTERNAL                      false
set_module_property  OPAQUE_ADDRESS_MAP            true
set_module_property  GROUP                         yogotie
set_module_property  AUTHOR                        "yogotie"
set_module_property  DISPLAY_NAME                  "I2C Stream"
set_module_property  INSTANTIATE_IN_SYSTEM_MODULE  true
set_module_property  EDITABLE                      true
set_module_property  REPORT_TO_TALKBACK            false
set_module_property  ALLOW_GREYBOX_GENERATION      false
set_module_property  REPORT_HIERARCHY              false


#
# file sets
#

# Synthesis Files
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""

set_fileset_property QUARTUS_SYNTH TOP_LEVEL i2c
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false

add_fileset_file  i2c.vhd          VHDL  PATH  ../vhdl/i2c.vhd          TOP_LEVEL_FILE
add_fileset_file  i2c_bit_rx.vhd   VHDL  PATH  ../vhdl/i2c_bit_rx.vhd
add_fileset_file  i2c_bit_tx.vhd   VHDL  PATH  ../vhdl/i2c_bit_tx.vhd
add_fileset_file  i2c_byte_rx.vhd  VHDL  PATH  ../vhdl/i2c_byte_rx.vhd
add_fileset_file  i2c_byte_tx.vhd  VHDL  PATH  ../vhdl/i2c_byte_tx.vhd
add_fileset_file  i2c_iobuf.vhd    VHDL  PATH  ../vhdl/i2c_iobuf.vhd
add_fileset_file  i2c_pkg.vhd      VHDL  PATH  ../vhdl/i2c_pkg.vhd

# Verilog simulation files
add_fileset SIM_VERILOG SIM_VERILOG "" ""

set_fileset_property SIM_VERILOG TOP_LEVEL i2c
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE true

add_fileset_file  i2c.vhd          VHDL  PATH  ../vhdl/i2c.vhd
add_fileset_file  i2c_bit_rx.vhd   VHDL  PATH  ../vhdl/i2c_bit_rx.vhd
add_fileset_file  i2c_bit_tx.vhd   VHDL  PATH  ../vhdl/i2c_bit_tx.vhd
add_fileset_file  i2c_byte_rx.vhd  VHDL  PATH  ../vhdl/i2c_byte_rx.vhd
add_fileset_file  i2c_byte_tx.vhd  VHDL  PATH  ../vhdl/i2c_byte_tx.vhd
add_fileset_file  i2c_iobuf.vhd    VHDL  PATH  ../vhdl/i2c_iobuf.vhd
add_fileset_file  i2c_pkg.vhd      VHDL  PATH  ../vhdl/i2c_pkg.vhd

# VHDL simulation files
add_fileset SIM_VHDL SIM_VHDL "" ""

set_fileset_property SIM_VHDL TOP_LEVEL i2c
set_fileset_property SIM_VHDL ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VHDL ENABLE_FILE_OVERWRITE_MODE true

add_fileset_file  i2c.vhd          VHDL  PATH  ../vhdl/i2c.vhd
add_fileset_file  i2c_bit_rx.vhd   VHDL  PATH  ../vhdl/i2c_bit_rx.vhd
add_fileset_file  i2c_bit_tx.vhd   VHDL  PATH  ../vhdl/i2c_bit_tx.vhd
add_fileset_file  i2c_byte_rx.vhd  VHDL  PATH  ../vhdl/i2c_byte_rx.vhd
add_fileset_file  i2c_byte_tx.vhd  VHDL  PATH  ../vhdl/i2c_byte_tx.vhd
add_fileset_file  i2c_iobuf.vhd    VHDL  PATH  ../vhdl/i2c_iobuf.vhd
add_fileset_file  i2c_pkg.vhd      VHDL  PATH  ../vhdl/i2c_pkg.vhd


#
# parameters
#
add_parameter           g_clock_freq_hz  STRING         100000000.0
set_parameter_property  g_clock_freq_hz  DEFAULT_VALUE  100000000.0
set_parameter_property  g_clock_freq_hz  DISPLAY_NAME   g_clock_freq_hz
set_parameter_property  g_clock_freq_hz  TYPE           STRING
set_parameter_property  g_clock_freq_hz  UNITS          None
set_parameter_property  g_clock_freq_hz  HDL_PARAMETER  true

add_parameter           g_i2c_freq_hz    STRING         100000.0
set_parameter_property  g_i2c_freq_hz    DEFAULT_VALUE  100000.0
set_parameter_property  g_i2c_freq_hz    DISPLAY_NAME   g_i2c_freq_hz
set_parameter_property  g_i2c_freq_hz    TYPE           STRING
set_parameter_property  g_i2c_freq_hz    UNITS          None
set_parameter_property  g_i2c_freq_hz    HDL_PARAMETER  true


#
# display items
#


#
# connection point clock
#
add_interface           clock  clock                end

set_interface_property  clock  clockRate            0
set_interface_property  clock  ENABLED              true
set_interface_property  clock  EXPORT_OF            ""
set_interface_property  clock  PORT_NAME_MAP        ""
set_interface_property  clock  CMSIS_SVD_VARIABLES  ""
set_interface_property  clock  SVD_ADDRESS_GROUP    ""

add_interface_port      clock  clk                  clk   Input  1


#
# connection point reset
#
add_interface           reset  reset                end

set_interface_property  reset  associatedClock      clock
set_interface_property  reset  synchronousEdges     DEASSERT
set_interface_property  reset  ENABLED              true
set_interface_property  reset  EXPORT_OF            ""
set_interface_property  reset  PORT_NAME_MAP        ""
set_interface_property  reset  CMSIS_SVD_VARIABLES  ""
set_interface_property  reset  SVD_ADDRESS_GROUP    ""

add_interface_port      reset  reset                reset     Input  1


#
# connection point sda
#
add_interface           sda  conduit              end

set_interface_property  sda  associatedClock      clock
set_interface_property  sda  associatedReset      ""
set_interface_property  sda  ENABLED              true
set_interface_property  sda  EXPORT_OF            ""
set_interface_property  sda  PORT_NAME_MAP        ""
set_interface_property  sda  CMSIS_SVD_VARIABLES  ""
set_interface_property  sda  SVD_ADDRESS_GROUP    ""

add_interface_port      sda  coe_sda_export       export  Bidir  1


#
# connection point scl
#
add_interface           scl  conduit              end

set_interface_property  scl  associatedClock      clock
set_interface_property  scl  associatedReset      ""
set_interface_property  scl  ENABLED              true
set_interface_property  scl  EXPORT_OF            ""
set_interface_property  scl  PORT_NAME_MAP        ""
set_interface_property  scl  CMSIS_SVD_VARIABLES  ""
set_interface_property  scl  SVD_ADDRESS_GROUP    ""

add_interface_port      scl  coe_scl_export       export  Bidir  1


#
# connection point rx
#
add_interface           rx  avalon_streaming            start

set_interface_property  rx  associatedClock             clock
set_interface_property  rx  associatedReset             reset
set_interface_property  rx  dataBitsPerSymbol           8
set_interface_property  rx  errorDescriptor             ACK
set_interface_property  rx  firstSymbolInHighOrderBits  true
set_interface_property  rx  maxChannel                  0
set_interface_property  rx  readyLatency                0
set_interface_property  rx  ENABLED                     true
set_interface_property  rx  EXPORT_OF                   ""
set_interface_property  rx  PORT_NAME_MAP               ""
set_interface_property  rx  CMSIS_SVD_VARIABLES         ""
set_interface_property  rx  SVD_ADDRESS_GROUP           ""

add_interface_port      rx  aso_rx_data                 data           Output  8
add_interface_port      rx  aso_rx_startofpacket        startofpacket  Output  1
add_interface_port      rx  aso_rx_endofpacket          endofpacket    Output  1
add_interface_port      rx  aso_rx_error                error          Output  1
add_interface_port      rx  aso_rx_valid                valid          Output  1
add_interface_port      rx  aso_rx_ready                ready          Input   1


#
# connection point tx
#
add_interface           tx  avalon_streaming            end

set_interface_property  tx  associatedClock             clock
set_interface_property  tx  associatedReset             reset
set_interface_property  tx  dataBitsPerSymbol           8
set_interface_property  tx  errorDescriptor             ACK
set_interface_property  tx  firstSymbolInHighOrderBits  true
set_interface_property  tx  maxChannel                  0
set_interface_property  tx  readyLatency                0
set_interface_property  tx  ENABLED                     true
set_interface_property  tx  EXPORT_OF                   ""
set_interface_property  tx  PORT_NAME_MAP               ""
set_interface_property  tx  CMSIS_SVD_VARIABLES         ""
set_interface_property  tx  SVD_ADDRESS_GROUP           ""

add_interface_port      tx  asi_tx_data                 data           Input   8
add_interface_port      tx  asi_tx_startofpacket        startofpacket  Input   1
add_interface_port      tx  asi_tx_endofpacket          endofpacket    Input   1
add_interface_port      tx  asi_tx_error                error          Input   1
add_interface_port      tx  asi_tx_valid                valid          Input   1
add_interface_port      tx  asi_tx_ready                ready          Output  1

